# Generated by Django 4.2.5 on 2023-11-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuserinfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserInfo',
        ),
    ]
