# Generated by Django 4.2.5 on 2023-11-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCategory',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
