# Generated by Django 4.2.5 on 2024-03-08 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('dislikes', models.PositiveIntegerField(default=0, null=True)),
                ('author', models.ManyToManyField(blank=True, null=True, to='forum.author')),
            ],
        ),
        migrations.CreateModel(
            name='Recension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('dislikes', models.PositiveIntegerField(default=0, null=True)),
                ('author', models.ForeignKey(on_delete=models.SET('Okänd användare'), to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.book')),
            ],
        ),
    ]
