# Generated by Django 5.0.1 on 2024-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_booklike_recensionlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recension',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recension',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
