# Generated by Django 5.0.1 on 2024-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_book_dislikes_alter_book_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recension',
            name='recension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
