# Generated by Django 5.0.1 on 2024-03-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_recension_recension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recension',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='recension',
            name='likes',
        ),
        migrations.DeleteModel(
            name='RecensionLike',
        ),
    ]
